CREATE TABLE ROLE(
   ID_ROLE INT AUTO_INCREMENT,
   LABELE VARCHAR(50)  NOT NULL,
   PRIMARY KEY(ID_ROLE)
);

CREATE TABLE CATEGORIE(
   ID_CATEGORIE INT AUTO_INCREMENT,
   NOM_CATEGORIE VARCHAR(50) ,
   PRIMARY KEY(ID_CATEGORIE)
);

CREATE TABLE UTILISATEUR(
   ID_UTILISATEUR INT AUTO_INCREMENT,
   NOM_UTILISATEUR VARCHAR(50) ,
   EMAIL_UTILISATEUR VARCHAR(255)  NOT NULL,
   MDP_UTILISATEUR VARCHAR(255)  NOT NULL,
   TOKEN_UTILISATEUR VARCHAR(50) ,
   ID_ROLE INT,
   PRIMARY KEY(ID_UTILISATEUR),
   FOREIGN KEY(ID_ROLE) REFERENCES ROLE(ID_ROLE)
);

CREATE TABLE PAGE(
   ID_PAGE INT AUTO_INCREMENT,
   TITRE_PAGE VARCHAR(50)  NOT NULL,
   CONTENU_PAGE TEXT NOT NULL,
   VISIBILITER_PAGE BOOLEAN,
   ID_UTILISATEUR INT,
   PRIMARY KEY(ID_PAGE),
   FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE URL(
   ID_URL INT AUTO_INCREMENT,
   CHEMIN_URL VARCHAR(50)  NOT NULL,
   ID_CATEGORIE INT,
   ID_PAGE INT,
   PRIMARY KEY(ID_URL),
   FOREIGN KEY(ID_CATEGORIE) REFERENCES CATEGORIE(ID_CATEGORIE),
   FOREIGN KEY(ID_PAGE) REFERENCES PAGE(ID_PAGE)
);
